---
- name: "Build with ansible"
  hosts: all
  become: yes  # If you need to run tasks with sudo
  tasks:
    - name: remove image
      command: docker rmi muhammadelmansi/depi_final
      ignore_errors: yes

    - name: build docker image using the Dockerfile
      command: docker build -t muhammadelmansi/depi_final .

    - name: Push Image to dockerhub
      command: docker push muhammadelmansi/depi_final
      ignore_errors: yes
      
    - name: stop and remove containers
      command: docker-compose down
      ignore_errors: yes

    - name: build docker-compose
      command: docker-compose up -d 
