---
- name: "Build with ansible"
  hosts: app_servers
  tasks:
    - name: pull image
      command: docker pull sharara99/depi_final:latest
      ignore_errors: yes

    - name: stop and remove containers
      command: docker-compose down
      ignore_errors: yes

    - name: build docker-compose
      command: docker-compose up -d 
