---
- name: "Build with ansible"
  hosts: app_servers
  become: yes  # If you need to run tasks with sudo
  tasks:
    - name: pull image
      command: docker pull sharara99/depi_final
      ignore_errors: yes

    - name: stop and remove containers
      command: docker-compose down
      ignore_errors: yes

    - name: build docker-compose
      command: docker-compose up -d 
